title: Shahzad Rasool
pronunciation: Sheh-zaad Rasool
position: Assistant Professor
affiliation: School of Interdisciplinary Engineering and Sciences (SINES)
previous_position: Fraunhofer IDM @ NTU, Singapore.
Research Fellow at Visual Immersive Haptic Mathematics (VIHAMAT) Lab.
thesis_link: 
profile_image: https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR3Gx9koJ_1uD8V9HwLs3JEu7wBu8zDNfsupw&s
intro_title: About
intro: |
  Dr. Shahzad Rasool is an Assistant Professor at School of Interdisciplinary Engineering and Sciences (SINES), National University of Science and Technology (NUST) since August 2016. He received his Ph.D. from Nanyang Technological University (NTU), Singapore in 2014, M.Sc. degree in Communication Engineering from Technische Universität München (TUM), Germany in 2009 and B.Sc. in Electrical Engineering from University of Engineering and Technology (UET), Taxila, Pakistan in 2006. In 2008, he worked as a research intern at DOCOMO Communications Laboratories Europe, Munich. From 2014-2016, he worked as a Research Fellow at the Immersive Mathematics Lab of Fraunhofer IDM @ NTU, Singapore. The recent focus of his research is on applications of immersive interaction and his research interests include haptics, virtual reality, HCI and computer vision.
intro_video: _ioc6sdgugo
google_scholar: https://scholar.google.com/citations?view_op=list_works&hl=en&hl=en&user=ERuoo-UAAAAJ
publication_tags:
  - HCI
  - HMI
  - Neuro
  - HCD
publications:
  - title: Interactive 3D visualization of chemical structure diagrams embedded in text to aid spatial learning process of students
    description: Students undertaking courses in the field of chemistry need to integrate their spatial skills and conceptual knowledge. However, model perception along with the understanding of spatial processes and spatial structures of molecules has been a cause of difficulty for students as conventional teaching methods cannot fully aid student comprehension. In this research, we propose a technological solution to aid the spatial learning process by automatically creating a link between two-dimensional (2D) representations of chemical structures and three-dimensional (3D) molecular visualization.
    image: https://pubs.acs.org/cms/10.1021/acs.jchemed.9b00690/asset/images/medium/ed9b00690_0008.gif
    tags: [HCI, HMI]
    paper: /path/to/paper.pdf
    video: https://youtube.com/watch?v=video-id
    project: /path/to/project
  # Add more publications as needed

  - title: Image-driven virtual simulation of arthroscopy
    description: In recent years, minimally invasive arthroscopic surgery has replaced a number of conventional open orthopedic surgery procedures on joints. While this achieves a number of advantages for the patient, the surgeons have to learn very different skills, since the surgery is performed with special miniature pencil-like tools and cameras inserted through little incisions while observing the surgical field on video monitor.
    image: https://s3.amazonaws.com/arthrex-video/videos/uAAzLcc8cU2xtgF14eTZYQ/thumbnails/uAAzLcc8cU2xtgF14eTZYQ_0.75_1920.jpg
    tags: [Neuro]
    paper: /path/to/paper.pdf
    video: https://youtube.com/watch?v=video-id
    project: /path/to/project